project_id = "wxpifygevyofkkankgtu"

[functions.plaid-exchange]
verify_jwt = false


[functions.demo-login]
verify_jwt = false

[functions.seed-demo-account]
verify_jwt = false

[functions.reset-demo-account]
verify_jwt = false
